version: '3.4'

networks:
  nginx-php83-mysql8:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php83-service
      - mysql8-service
    networks:
      - nginx-php83-mysql8

  # php
  php83-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-container
    volumes:
      - ./:/var/www/project
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - nginx-php83-mysql8

 # mysql
  mysql8-service:
    image: mysql:8.0.32
    container_name: mysql8-container
    ports:
      - "4306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - nginx-php83-mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
