parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Calculator\PriceCalculator:
        tags: ['price_calculator']

    App\Service\Calculator\VatCalculator:
        tags: ['vat_calculator']

    App\Service\Collector\PriceCalculatorCollector:
        arguments:
            $priceCalculator: !tagged price_calculator

    App\Service\Collector\VatCalculatorCollector:
        arguments:
            $vatCalculator: !tagged vat_calculator
